### ISSUE TITLE
Glove 300d missing from main directory?

### ISSUE THREAD

**Issue by dhvalden** [Nish-19/Misinformation-Novelty-Emotion#1]
In the instructions to reproduce it is mentioned that glove-300d has to be placed in novelty_module/resources, but glove-300d is not present.

**Comment by Nish-19** [comment]
Hi, 

Due to file size uploading constraints, I have not uploaded the Glove pre-trained embeddings file here. 

You can download the glove.6B.zip file from https://github.com/stanfordnlp/GloVe and put it in the resources directory.

**Comment by dhvalden** [comment]
Thanks a lot for your reply!
